name: Deploy to Hostinger (qgoproject)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: hostinger-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}           # ftp.forestgreen-elephant-353388.hostingersite.com
          username: ${{ secrets.FTP_USERNAME }}     # u345343285.aakkiiff
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}             # 21
          protocol: ftp
          server-dir: ./                            # jailed to public_html/qgoproject/ (note the /)
          local-dir: public/                        # NOTE: trailing slash
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/README.md
            **/.env
